### ISSUE TITLE
mixed mode (encrypted + plain data bags) with secret file specified in knife.rb

### ISSUE THREAD

**Issue by rmoriz** [thbishop/knife-solo_data_bag#25]
When specified in a knife.rb:

e.g.

```
knife[:secret_file]   = File.expand_path('../../test/integration/encrypted_data_bag_secret', __FILE__)
```

knife-solo_data_bag will encrypt new data bags, if they contain an array. However I haven't found a way to disable this (I don't want to encrypt all my data bags).

**Comment by joeyates** [comment]
What you're seeing is the standard behavior: all encrypted or none encrypted. I think it is unlikely that a change can be made to support mixed encrypted and clear text data bags,
