### ISSUE TITLE
Example how to use data bags in recipes?

### ISSUE THREAD

**Issue by xanview** [thbishop/knife-solo_data_bag#26]
I checked the knife-solo_data_bag documentation but I cannot for the life of me find an example how to access the data in those data bags in my recipes?

**Comment by AnneTheAgile** [comment]
@hackeron , did you read the docs? 
1.[] ; ; ; ; ; X.Knife-solo data bag by thbishop ; ; http://thbishop.com/knife-solo_data_bag/
