### ISSUE TITLE
With recent chef client this doesn't work

### ISSUE THREAD

**Issue by onknows** [thbishop/knife-solo_data_bag#30]
This things looks broken with Chef client 12.4.1

After installation knife will just complain that command knife solo does not exist.

**Comment by jaseeey** [comment]
I'm running the following versions:
* Chef Development Kit Version: 0.10.0
* chef-client version: 12.5.1
* berks version: 4.0.1
* kitchen version: 1.4.2

When trying to access `knife solo` commands, it throws a fatal error stating that it cannot find the subcommand for 'solo' along with a list of usable commands.

Are there any suggestions to work-around this issue?

**Comment by jaseeey** [comment]
I managed to get around this issue by uninstalling the ChefDK and using RVM and RubyGems to manually install Chef Solo and its components. Once this was done, I was able to use `knife solo` without any problems running Chef 12.6.0.

**Comment by printfbabu** [comment]
Uninstalling ChefDK is not needed. Just create a new gemset.

```
rvm use 2.2@databags
gem install knife-solo
gem install knife-solo_data_bag
```

Works for me

**Comment by mangust404** [comment]
I have a similar issue even after installing a new rvm gemset. In my case the error was that I forgot to include "gem knife-solo_data_bag" into my Gemfile.

**Comment by joeyates** [comment]
Hello @onknows,

Are you still having this issue? If so, could you indicate the minimal steps necessary to reproduce the problem?

**Comment by onknows** [comment]
@joeyates this is not an issue for me because I am using this plugin. I can't remember at this point what I wanted to use this plugin for but I think I must have found another way of doing what I want to do.
