### ISSUE TITLE
Broken in Chef 12.11, recommend `knife data bag --local-mode`

### ISSUE THREAD

**Issue by andytson-inviqa** [thbishop/knife-solo_data_bag#34]
The following made Chef 12.10.54 (unreleased) stop working with knife-solo_data_bag.
https://github.com/chef/chef/compare/v12.10.53...v12.10.54

Since Chef local-mode has supported local editing of data bags since I think 11.8, I don't think this gem is needed anymore.

Local mode can be induced alternatively via adding to knife.rb:

```
local_mode true
```

**Comment by drspeedo** [comment]
The issue with that is that local_mode reads from your knife.rb and uses the chef-repo.  'knife solo data bag' is still helpful If you keep data bags in test/integration for kitchen and want the ability to modify encrypted data bags.

**Comment by joeyates** [comment]
Can you confirm you are still having issues with the latest version of this gem (>=2.0)?
Please use `local_mode true` in your config when testing, thanks.
